<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td><strong>{{ $score->points }}</strong></x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
<x-table.td>-</x-table.td>
